project:
  type: book
  output-dir: docs

book:
  title: "Modern inference methods for non-probability samples with R"
  author: "Łukasz Chrostowski, Maciej Beręsewicz"
  sidebar:
    background: light
  page-navigation: true
  repo-url: https://github.com/ncn-foreigners/nonprobsvy-book
  site-url: https://ncn-foreigners.github.io/nonprobsvy-book/
  search: true
  downloads: [pdf, epub]
  repo-branch: main
  repo-actions: [issue]
  chapters:
    - index.qmd
    - 01-Introduction.qmd
    - 02-Case-Study.qmd
    - 03-Inverse-Probability-Weighting.qmd
    - 04-Mass-Imputation.qmd
    - 05-Doubly-Robust-Estimation.qmd
    - 06-Advanced-Topics.qmd
    - 07-Summary.qmd
    - 10-References.qmd
  appendices: 
    - text: "Appendix A: Additional Material"
      file: 08-Appendix.qmd
    - text: "Appendix B: Nomenclature"
      file: 09-Nomenclature.qmd

bibliography: references.bib

format:
  html:
    include-in-header:
     - file: macros.html
    theme: cosmo
    fontsize: 1em
    linestretch: 1.5
  pdf:
    documentclass: scrreprt
    toc: true
    number-sections: true
    colorlinks: true
    papersize: letter
    geometry:
      - margin=1in
    include-in-header:
      - macros.tex

editor: visual