project:
  type: book
  output-dir: docs

book:
  title: "Modern inference methods for non-probability samples with R"
  author: "Łukasz Chrostowski, Maciej Beręsewicz"
  sidebar:
    background: light
  page-navigation: true
  theme:
    dark: darkly
  repo-url: https://github.com/ncn-foreigners/nonprobsvy-book
  site-url: https://ncn-foreigners.github.io/nonprobsvy-book/
  search: true
  downloads: [pdf, epub]
  repo-branch: main
  repo-actions: [issue]
  chapters:
    - index.qmd
    - intro.qmd
    - ipw.qmd
    - mi.qmd
    - dr.qmd
    - variableselection.qmd
    - summary.qmd
    - references.qmd
  appendices: 
    - appendix.qmd
    - nomenclature.qmd

bibliography: references.bib

format:
  html:
    include-in-header:
     - file: macros.html
    theme: cosmo
    fontsize: 2.6em
    linestretch: 2.6
  pdf:
    documentclass: scrreprt

editor: visual