project:
  type: book
  output-dir: docs

book:
  title: "Modern inference methods for non-probability samples with R"
  author: "Łukasz Chrostowski, Maciej Beręsewicz"
  date: "4/20/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - ipw.qmd
    - mi.qmd
    - dr.qmd
    - variableselection.qmd
    - summary.qmd
    - appendix.qmd
    - references.qmd

bibliography: references.bib


format:
  html:
    include-in-header:
     - file: macros.html
    theme: cosmo
    fontsize: 0.9em
    linestretch: 1.5
  pdf:
    documentclass: scrreprt

editor: visual