project:
  type: book
  output-dir: docs

book:
  title: "Modern inference methods for non-probability samples with R"
  author: "Łukasz Chrostowski, Maciej Beręsewicz, Bartosz Bogulas, Cyprian Jurkowski"
  
  # do we want to have any color here ?? 
  sidebar:
    background: light
    
  page-footer:
    left: |
      Modern inference methods for non-probability samples with R
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.  
  
  # should we add reader mode ?? 
  reader-mode: false
  page-navigation: true
  search: true
  cover-image: images/logo.png
  favicon: images/logo.png
  repo-url: https://github.com/ncn-foreigners/nonprobsvy-book
  site-url: https://ncn-foreigners.github.io/nonprobsvy-book/
  downloads: [pdf, epub]
  repo-branch: main
  repo-actions: [edit, issue]
  
  chapters:
    - index.qmd
    - Introduction.qmd
    - Case-Study.qmd
    
    # later division into parts will be added
    
    # - part: nonprob_function.qmd
    #chapters:
  
    - Inverse-Probability-Weighting.qmd
    - Mass-Imputation.qmd
    - Doubly-Robust-Estimation.qmd
    
    # - part: metohod_selection.qmd
    #chapters:
    # - logit.qmd
    # - probit.qmd
    # - cloglog.qmd
    
    # - part: metohod_outcome.qmd
    #chapters:
    
    # - part: family_outcome.qmd
    #chapters:
    
    # - part: data_analysis_examples.qmd
    #chapters:
    
    # - part: inference_methods_and_variance_estimation.qmd
    #chapters:
    
    - Advanced-Topics.qmd
    
  #chapters:  
    - Summary.qmd
    - References.qmd
    
  appendices: 
    - text: "Appendix A: Additional Material"
      file: Appendix.qmd
    - text: "Appendix B: Nomenclature"
      file: Nomenclature.qmd

bibliography: references.bib

format:
  html:
    include-in-header:
     - file: macros.html
    theme: 
      light: flatly
      dark: darkly
    fontsize: 1em
    linestretch: 1.5
    
  pdf:
    documentclass: scrreprt
    toc: true
    number-sections: true
    colorlinks: true
    papersize: letter
    geometry:
      - margin=1in
    include-in-header:
      - macros.tex

editor: visual